### PR TITLE
fix #791

### LINKED ISSUE #791: DEBUG CRASHSERVER command
This would require operator permissions (like the rest of `DEBUG`). You'd enter `debug crashserver 4758281` (a confirmation code, like with `NS UNREGISTER`) and it would cause an unhandled panic on the server. This could be used to test failover in k8s and other settings.

### PR DESCRIPTION
**Pull request by slingamn**

### CODE REVIEW

**Comment by slingamn** [comment]
As discussed, this is not configurable, but it requires the `oper:rehash` permission (which is only suitable for someone with systems-level access to the server) and a confirmation code.

File: irc/handlers.go [hunk 1]
```diff
@@ -804,6 +804,26 @@ func debugHandler(server *Server, client *Client, msg ircmsg.IrcMessage, rb *Res
 	case "STOPCPUPROFILE":
 		pprof.StopCPUProfile()
 		rb.Notice(fmt.Sprintf("CPU profiling stopped"))
+
+	case "CRASHSERVER":
+		if !client.HasRoleCapabs("oper:rehash") {
+			rb.Notice(client.t("You must have rehash permissions in order to execute DEBUG CRASHSERVER"))
+			return false
+		}
+		code := unregisterConfirmationCode(server.name, server.ctime)
```
Comment (csmith) [inline irc/handlers.go]: Might be nice if this is pulled out of chanserv.go and named something more generic?
