### PR TITLE
fix #764

### LINKED ISSUE #764: `hostserv take` with a request pending should succeed and cancel your request
This is a confusing UX thing. If you request, then you take, your take will fail due to throttling and your request will still be pending.

### PR DESCRIPTION
**Pull request by slingamn**

### CODE REVIEW

File: irc/hostserv.go [hunk 1]
```diff
@@ -415,9 +420,8 @@ func hsTakeHandler(server *Server, client *Client, command string, params []stri
 		} else {
 			hsNotice(rb, client.t("An error occurred"))
 		}
-	} else if vhost != "" {
-		hsNotice(rb, client.t("Successfully set vhost"))
 	} else {
-		hsNotice(rb, client.t("Successfully cleared vhost"))
+		hsNotice(rb, client.t("Successfully set vhost"))
+		server.snomasks.Send(sno.LocalVhosts, fmt.Sprintf("Client %s (account %s) took vhost %s", client.Nick(), account, vhost))
```
Comment (DanielOaks) [inline irc/hostserv.go]: this line brings up a question for me: should we translate snomask lines to the default server language? if so we'll want to make this use the `%[1]s` `%[2]s` stuff instead
