### PR TITLE
fix #410

### LINKED ISSUE #410: `ns register` is hard to use
A user was doing `ns register account passphrase email`, i.e., passphrase and email were transposed. Account registration appeared to succeed, but then they couldn't log into the account (because oragono expected the email as the passphrase).

Let's either detect this or send a response that helps people figure out they've done it wrong, e.g.,

dan-: maybe spit out a line like "account <blah> registered with email address <blah> so that people can see if they have managed to mix around the params

### PR DESCRIPTION
**Pull request by slingamn**
Tested manually, including whitespace preservation on `HS REJECT`.

### CODE REVIEW

File: irc/nickserv.go [hunk 1]
```diff
@@ -586,20 +587,25 @@ func nsInfoHandler(server *Server, client *Client, command string, params []stri
...
+		email = params[1]
 	}
 
 	certfp := client.certfp
-	if passphrase == "" && certfp == "" {
-		nsNotice(rb, client.t("You need to either supply a passphrase or be connected via TLS with a client cert"))
-		return
+	if passphrase == "*" {
+		if certfp == "" {
+			nsNotice(rb, client.t("You need to either supply a passphrase or be connected via TLS with a client cert"))
```
Comment (DanielOaks) [inline irc/nickserv.go]: let's change this message to: _"You must be connected with TLS to use a client certificate"_

Comment (slingamn) [reply irc/nickserv.go]: How about: "You must be connected via TLS with a client certificate to do this"?

Comment (DanielOaks) [reply irc/nickserv.go]: Hmm, let's split the difference: "You must be connected with TLS and a client certificate to do this", using 'connected via TLS' just feels a touch off
